schemaVersion: 2.2.0
metadata:
  name: ansible-demo
starterProjects:
  - name: playbook-starter
    git:
      remotes:
        origin: https://github.com/hyperkineticnerd/ansible-playbook-template
  - name: collection-starter
    git:
      remotes:
        origin: https://github.com/hyperkineticnerd/ansible-collection-template
components:
  - name: tooling-container
    container:
      image: quay.io/mloriedo/ansible-creator-ee:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
commands:
  - id: oc-install
    exec:
      commandLine: '/usr/local/bin/ansible-playbook ${PROJECT_SOURCE}/playbooks/install_oc.yml'
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
        isDefault: true
      component: tooling-container
events:
  postStart:
    - "oc-install"
