---
- name: Hello World Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello World"
    - debug: 
        msg: "I am poorly written"